<?php  /** */ ?>
<?php if ($this->isActive()): 
		
	?>
		
   
	
	 <script type="text/javascript">
	
	if (typeof(jQuery) == 'undefined') {
	   document.write("<script type='text/javascript' src='//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js'></scr"+"ipt>");
    }
	</script> 
	
			
	<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-T55T8X"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-T55T8X'); 

</script> 
<!-- End Google Tag Manager -->

	<script type="text/javascript">
	
        (function(i, s, o, g, r, a, m) {
            i["GoogleAnalyticsObject"] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, "script", "//www.google-analytics.com/analytics.js", "ga");
	
     ga('create', '<?php echo $this->getAccountId(); ?>','<?php echo $this->getRequest()->getHttpHost() ?>');
       
		
        ga("require", "displayfeatures");
		ga('send', 'pageview');
		ga("require", "ec", "ec.js");
		
        var $t_jQuery = jQuery.noConflict(); 
		
		<?php 
		if($this->getBrandAttr()  !== ''){
			$brand_code = $this->getBrandAttr();
		}
		else{
			$brand_code = '';
		}
			function t_getBrandValue($product,$t_brand_code){
				
					if($t_brand_code != ''){
						
						$t_brand = $product->getResource()->getAttribute($t_brand_code);
						if($t_brand){
							return addslashes(trim($t_brand ->getFrontend()->getValue($product)));
						}
						else{
							return '';
						}
					}
					else{
						return '';
					}
			}
			
    $routeName = Mage::app()->getRequest()->getRouteName();
    $identifier = Mage::getSingleton('cms/page')->getIdentifier();
    if ($routeName == 'cms' && $identifier == 'home') :   
    ?>	
			exec_tvc_t_hi = true;
		
				
	<?php 

	endif; 

	
	if (strpos($this->getRequest()->getPathInfo(), 'checkout/cart/') !== false) : ?>
			
            var cartProducts = {};
			
        <?php
        $cart = Mage::getModel('checkout/cart')->getQuote();
		$catIds = "";
								
        foreach ($cart->getAllItems() as $item) {
		
            ?>
				<?php $cats = $item->getProduct()->getCategoryIds();
								foreach ($cats as $category_id) {
								   $_cat = Mage::getModel('catalog/category')->load($category_id) ;
								   $catIds.=$_cat->getName().","; 
								   
								   }
								  
									$_item = $item->getProduct()->getId();
									$_resource = $item->getProduct()->getResource();
									$optionValue = $_resource->getAttributeRawValue($_item, $this->getBrandAttr(), Mage::app()->getStore());
									$product_sku = $item->getProduct()->getSku();
									if($product_sku == ""):
										$product_sku = $_item;
									endif;
									$productId = $item->getProduct()->getId();
									$_product = Mage::getModel('catalog/product')->load($productId);
								   ?>
			
                cartProducts['<?php echo $item->getProduct()->getProductUrl(); ?>'] = {'sku': '<?php echo addslashes($product_sku); ?>',
                    'Name': '<?php echo addslashes($item->getProduct()->getName()); ?>',
                    'id': '<?php echo $item->getProduct()->getId(); ?>',
                    'qty': '<?php echo $item->getQty(); ?>',
                    'Price': '<?php echo $item->getProduct()->getFinalPrice(); ?>',
					'categories':'<?php echo addslashes(trim($catIds,",")); ?>',
					'brand':'<?php echo addslashes(t_getBrandValue($_product,$brand_code)); ?>'
                }
		
            <?php $catIds = "";
        }
        ?>
			ga('set', '&cu', '<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>');
           exec_tvc_t_dc = true;

    <?php endif; ?>
       
    <?php if (Mage::app()->getRequest()->getControllerName() === "category"): ?>
			
            exec_tvc_t_c = true;
            
    <?php endif; ?>

        

    <?php
    if (strpos($this->getRequest()->getPathInfo(), '/catalogsearch/result/') !== false):
        ?>
		
			exec_tvc_t_cs = true;
           
    <?php endif;
    
	if ($this->getProduct()): ?>
		//	ga('set', '&cu', '<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>');
         //  exec_tvc_t_ppv = true;

        <?php
		
		if(isset($_COOKIE['tvc_metadata'])){
		
		
		}//end cookie block
		
        $sku_id = $this->getProduct()->getId();
        $product = Mage::getModel('catalog/product')->load($sku_id);
        
		$catIds = "";
								$product_sku = $product->getSku();
								if($product_sku == ""):
									$product_sku = $sku_id;
								endif;
        ?>
        	<?php $cats = $this->getProduct()->getCategoryIds();
								foreach ($cats as $category_id) {
								   $_cat = Mage::getModel('catalog/category')->load($category_id) ;
								   $catIds.=$_cat->getName().","; 
								   
								   }
						
								   ?>
            productObject = {
                'sku': '<?php echo addslashes($product_sku); ?>',
                'Name': '<?php echo addslashes($this->getProduct()->getName()) ?>',
                'Price': '<?php echo $this->getProduct()->getFinalPrice() ?>',
				'categories':'<?php echo addslashes(trim($catIds,",")); ?>',
				'brand':'<?php echo addslashes(t_getBrandValue($this->getProduct(),$brand_code)); ?>'
            }
			ga('set', '&cu', '<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>');
           exec_tvc_t_ppv = true;

         <?php   
		 if(isset($_COOKIE['tvc_metadata'])):
		$tvc_metadata = array(
							  'plugin_version'=>'2.0.0',
							  'current_pkg'=>Mage::getDesign()->getPackageName(),
							  'current_theme'=>Mage::getDesign()->getTheme('frontend'),
							  'Plugin_data'=>array('checkout_url'=>Mage::getStoreConfig('tatvic_uaee/ecommerce/checkout_url'),
													'success_url'=>Mage::getStoreConfig('tatvic_uaee/ecommerce/success_url'),
													'code_of_brand'=>Mage::getStoreConfig('tatvic_uaee/ecommerce/brand'),
													'Uninstall_mail'=>Mage::getStoreConfig('tatvic_uaee/general/uninstallMail'),
													'Install_mail'=>Mage::getStoreConfig('tatvic_uaee/general/installMail'),
													'visibility'=>$this->getProduct()->getVisibility(),
													'instock'=>Mage::getModel('cataloginventory/stock_item')->loadByProduct($sku_id)->getIsInStock(),
													'stock'=>Mage::getModel('cataloginventory/stock_item')->loadByProduct($sku_id)->getQty()
													));
							  
		//==============================
		?>var tvc_metadata = <?php echo json_encode($tvc_metadata); ?>;
		
		<?php
		endif;

	endif;
	
	if ($this->isCheckout() && !$this->isEcommerce()): 
		
	?>
          
            var cartObject = {};
			
		
        <?php
		
		
        $cart = Mage::getModel('checkout/cart')->getQuote();
		
		if ($this->helper('customer')->isLoggedIn()): ?>
			var checkoutStep = 2;
			var LoggedIn = true;
			
			<?php else : ?>
			var checkoutStep = 1;
		
			var LoggedIn = false;
			<?php endif; 
			$catIds = "";
			$items = $cart->getAllItems();
        foreach ($items as $itemId=>$item) {

            $productId = $item->getProduct()->getId();
            $productPrice = $item->getProduct()->getFinalPrice();
            $productSku = $item->getProduct()->getSku();
            $productName = $item->getProduct()->getName();
            $productQty = $item->getQty();
			$productBrand = $item->getData('brand');
			
			$_item = $item->getProduct()->getId();
			$_resource = $item->getProduct()->getResource();
			$optionValue = $_resource->getAttributeRawValue($_item, $this->getBrandAttr(), Mage::app()->getStore());
			//echo $optionvalue;
			$_product = Mage::getModel('catalog/product')->load($productId);
            ?>
			
				
				 <?php $cats = $item->getProduct()->getCategoryIds();
								foreach ($cats as $category_id) {
								   $_cat = Mage::getModel('catalog/category')->load($category_id) ;
								
								   $catIds.=$_cat->getName().","; 
								   
								   }
									$product_sku = $item->getProduct()->getSku();
									if($product_sku == ""):
										$product_sku = $_item;
									endif;
								   ?>
								   
                cartObject['<?php echo $item->getProduct()->getProductUrl(); ?>'] = {
                    'sku': '<?php echo addslashes($product_sku) ?>',
                    'Name': '<?php echo addslashes($productName) ?>',
                    'Price': '<?php echo $productPrice ?>',
                    'qty': '<?php echo $productQty ?>',
					'categories':'<?php echo addslashes(trim($catIds,",")); ?>',
					'brand':'<?php echo addslashes(t_getBrandValue($_product,$brand_code)); ?>'
                }
		
        <?php $catIds=""; } 
		
		
		?>
            exec_tvc_t_cobj = true;
			
    <?php endif; ?>
    <?php if ($this->isEcommerce()): ?>
		
        <?php
        $_order = $this->getOrder();
        $order = Mage::getModel('sales/order')->load($_order->getData($this->getTransactionIdField()));
        $items = $order->getAllItems();
        $data = array();
        $i = 0;
        ?>

            ga('set', '&cu', '<?php echo $_order->getOrderCurrencyCode(); ?>');
            var orderObject = {};
        
		<?php
		$catIds = "";
        foreach ($items as $itemId => $item) {
            ?>
			<?php $cats = $item->getProduct()->getCategoryIds();
								foreach ($cats as $category_id) {
								   $_cat = Mage::getModel('catalog/category')->load($category_id) ;
								   $catIds.=$_cat->getName().","; 
								   
								   }
									$product_sku = $item->getSku();
									if($product_sku == ""):
										$product_sku = $item->getId();
									endif;
									
									$productId = $item->getProduct()->getId();
									$_product = Mage::getModel('catalog/product')->load($productId);
								
								   ?>
								   
                orderObject['<?php echo $i ?>'] = {
                    'sku': '<?php echo addslashes($product_sku); ?>',
                    'Name': '<?php echo addslashes($item->getName()); ?>',
                    'Price': '<?php echo $item->getProduct()->getFinalPrice(); ?>',
                    'qty': '<?php echo $item->getQtyToInvoice(); ?>',
					'categories':'<?php echo addslashes(trim($catIds,",")); ?>',
					'brand':'<?php echo addslashes(t_getBrandValue($_product,$brand_code)) ?>'
                }
            <?php $catIds="";
            $i++;
        }
		$catIds = "";
        ?>
                    var transactionObject = {};
                    transactionObject = {
                        'tid': '<?php echo $_order->getData($this->getTransactionIdField()) ?>',
                        'aid': '<?php echo addslashes(Mage::app()->getStore()->getName()) ?>',
                        'revenue': '<?php echo $_order->getGrandTotal() ?>',
                        'tax': '<?php echo $_order->getTaxAmount() ?>',
                        'shipping': '<?php echo $_order->getShippingInclTax() ?>',
                        'ccode': '<?php echo addslashes($_order->getCouponCode()); ?>'
                    }
				//t_oid = '<?php echo $_order->getIncrementId();//?>';
					exec_tvc_t_thnx = true;


				
    <?php endif; ?>
    </script>
    
    <!--Tatvic Enhanced eCommerce Section end -->
<?php 
		
endif; ?>